const item = {
    id: 4922844661,
    title: "Sac eastpak neuf",
    brand_id: 303,
    size_id: null,
    status_id: 6,
    user_id: 19620151,
    country_id: 16,
    catalog_id: 1257,
    color1_id: 4,
    color2_id: 17,
    package_size_id: 1,
    is_unisex: 0,
    moderation_status: 0,
    is_hidden: false,
    is_visible: true,
    is_closed: false,
    favourite_count: 0,
    active_bid_count: 0,
    description: "Envoi rapide et soigné",
    package_size_standard: true,
    item_closing_action: null,
    related_catalog_ids: [],
    related_catalogs_enabled: false,
    size: "",
    brand: "Eastpak",
    composition: "",
    extra_conditions: "",
    disposal_conditions: 4,
    is_for_sell: true,
    is_handicraft: false,
    is_processing: false,
    is_draft: false,
    is_reserved: false,
    label: "Eastpak",
    original_price_numeric: "129.83",
    currency: "PLN",
    price_numeric: "129.83",
    last_push_up_at: "2024-08-22T16:30:21+02:00",
    created_at_ts: "2024-08-22T16:30:21+02:00",
    updated_at_ts: "2024-08-22T16:30:23+02:00",
    user_updated_at_ts: "2024-08-22T16:30:23+02:00",
    is_delayed_publication: false,
    photos: [
        {
            id: 19970780721,
            image_no: 1,
            width: 600,
            height: 800,
            dominant_color: "#A4C6C3",
            dominant_color_opaque: "#E4EEED",
            url: "https://images1.vinted.net/t/01_00583_aoZ9RipGdEsHzu3G9iUSSo8a/f800/1724337021.jpeg?s=843cefb0f3521edf0b206f2dd5a108e0b699e5e4",
            is_main: true,
            thumbnails: [Array],
            high_resolution: [Object],
            is_suspicious: false,
            full_size_url: "https://images1.vinted.net/tc/01_00583_aoZ9RipGdEsHzu3G9iUSSo8a/1724337021.jpeg?s=f24f0dfbf6f1888a99cce9642dc53d19ced700ce",
            is_hidden: false,
            extra: {}
        },
        {
            id: 19970780723,
            image_no: 2,
            width: 600,
            height: 800,
            dominant_color: "#9DAEA7",
            dominant_color_opaque: "#E2E7E5",
            url: "https://images1.vinted.net/t/02_0177a_2inLzUFfr4Asgxvxmq7QFGUB/f800/1724337021.jpeg?s=065e431e6e74feb3d451688e1fdf6da89029f417",
            is_main: false,
            thumbnails: [Array],
            high_resolution: [Object],
            is_suspicious: false,
            full_size_url: "https://images1.vinted.net/tc/02_0177a_2inLzUFfr4Asgxvxmq7QFGUB/1724337021.jpeg?s=a329c3cac0b1f1c41470f2a8fd03ea034ebe3441",
            is_hidden: false,
            extra: {}
        }
    ],
    can_be_sold: true,
    can_feedback: false,
    item_reservation_id: null,
    promoted_until: null,
    promoted_internationally: null,
    discount_price_numeric: null,
    author: null,
    book_title: null,
    isbn: null,
    measurement_width: null,
    measurement_length: null,
    measurement_unit: null,
    manufacturer: null,
    manufacturer_labelling: null,
    transaction_permitted: true,
    video_game_rating_id: null,
    item_attributes: [],
    "haov_item?": false,
    user: {
        id: 19620151,
        anon_id: "57278edf-9de3-42f2-a3cf-494836a05ae1",
        login: "alexetelo",
        real_name: null,
        email: null,
        birthday: null,
        item_count: 222,
        given_item_count: 1368,
        taken_item_count: 309,
        followers_count: 50,
        following_count: 16,
        following_brands_count: 1,
        positive_feedback_count: 1284,
        neutral_feedback_count: 6,
        negative_feedback_count: 16,
        meeting_transaction_count: 0,
        account_status: 0,
        feedback_reputation: 0.9800000000000001,
        feedback_count: 1306,
        is_on_holiday: false,
        is_publish_photos_agreed: true,
        expose_location: true,
        third_party_tracking: true,
        default_address: null,
        last_loged_on_ts: "2024-08-22T16:25:47+02:00",
        city_id: 68958,
        city: "Tracy-le-Mont",
        country_id: 16,
        country_code: "FR",
        country_iso_code: "FR",
        country_title: "France",
        contacts_permission: null,
        contacts: null,
        photo: {
            id: 12581493,
            width: 800,
            height: 798,
            temp_uuid: null,
            url: "https://images1.vinted.net/t/02_026c4_zPaZkaMV6xFtm85sWCMkwUty/f800/1605238918.jpeg?s=29f148a168a010871b09952498e366aa3dbfb777",
            dominant_color: "#31abc2",
            dominant_color_opaque: "#C1E6ED",
            thumbnails: [Array],
            is_suspicious: false,
            orientation: null,
            high_resolution: [Object],
            full_size_url: "https://images1.vinted.net/tc/02_026c4_zPaZkaMV6xFtm85sWCMkwUty/1605238918.jpeg?s=7548709100f35ac37a5f732587c4241ec470eab0",
            is_hidden: false,
            extra: {}
        },
        path: "/member/19620151-alexetelo",
        moderator: false,
        is_catalog_moderator: false,
        is_catalog_role_marketing_photos: false,
        hide_feedback: false,
        allow_direct_messaging: true,
        bundle_discount: {
            id: 2617807,
            user_id: 19620151,
            enabled: true,
            minimal_item_count: 2,
            fraction: "0.05",
            discounts: [Array]
        },
        fundraiser: null,
        business_account_id: null,
        has_ship_fast_badge: false,
        total_items_count: 1590,
        about: "",
        verification: { email: [Object], facebook: [Object], google: [Object] },
        avg_response_time: null,
        carrier_ids: [27, 50, 59, 97, 117, 135, 143, 4, 9, 10],
        carriers_without_custom_ids: [27, 50, 59, 97, 117, 135, 143, 4],
        locale: "fr",
        updated_on: 1724337023,
        is_hated: false,
        hates_you: false,
        is_favourite: false,
        profile_url: "https://www.vinted.pl/member/19620151-alexetelo",
        share_profile_url: "https://www.vinted.pl/member/19620151-alexetelo",
        facebook_user_id: null,
        is_online: true,
        can_view_profile: true,
        can_bundle: true,
        country_title_local: "Francja",
        last_loged_on: "dziś 16:25",
        accepted_pay_in_methods: [[Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object]],
        localization: "none",
        is_bpf_price_prominence_applied: true,
        msg_template_count: 0,
        account_ban_date: null,
        is_account_ban_permanent: false,
        business_account: null,
        business: false
    },
    conversion: {
        seller_price: "30.0",
        seller_currency: "EUR",
        buyer_currency: "PLN",
        fx_rounded_rate: "4.33",
        fx_base_amount: "1.0",
        fx_markup_rate: "0.012"
    },
    price: { amount: "129.83", currency_code: "PLN" },
    discount_price: null,
    service_fee: "7.19",
    total_item_price: "137.02",
    can_edit: false,
    can_delete: false,
    can_reserve: false,
    can_mark_as_sold: false,
    can_transfer: false,
    instant_buy: true,
    can_close: false,
    can_buy: true,
    can_bundle: true,
    can_ask_seller: true,
    can_favourite: false,
    user_login: "alexetelo",
    city_id: 68958,
    city: "Tracy-le-Mont",
    country: "France",
    promoted: false,
    is_mobile: false,
    bump_badge_visible: false,
    brand_dto: {
        id: 303,
        title: "Eastpak",
        slug: "eastpak",
        favourite_count: 24686,
        pretty_favourite_count: "24.7K",
        item_count: 235456,
        pretty_item_count: "235.5K",
        is_visible_in_listings: true,
        requires_authenticity_check: true,
        is_luxury: true,
        is_hvf: true,
        path: "/brand/303-eastpak",
        url: "https://www.vinted.pl/brand/303-eastpak",
        is_favourite: false
    },
    catalog_branch_title: "Dzieci → Ubranka dla chłopców → Torby i plecaki",
    path: "/items/4922844661-sac-eastpak-neuf",
    url: "https://www.vinted.pl/items/4922844661-sac-eastpak-neuf",
    accepted_pay_in_methods: [
        {
            id: 1,
            code: "CREDIT_CARD",
            requires_credit_card: true,
            event_tracking_code: "cc",
            icon: "credit-card",
            enabled: true,
            translated_name: "Karta płatnicza",
            note: "Osoba sprzedająca nie zobaczy twoich danych płatniczych.",
            method_change_possible: true
        },
        {
            id: 12,
            code: "P24",
            requires_credit_card: false,
            event_tracking_code: "p24",
            icon: "p24",
            enabled: true,
            translated_name: "Przelewy24",
            note: "",
            method_change_possible: true
        },
        {
            id: 18,
            code: "BLIK_DIRECT",
            requires_credit_card: false,
            event_tracking_code: "blik_direct",
            icon: "blik",
            enabled: true,
            translated_name: "Blik",
            note: "",
            method_change_possible: true
        }
    ],
    created_at: "dziś 16:30",
    color1: "Beżowy",
    color2: "Turkus",
    size_title: "",
    description_attributes: [],
    video_game_rating: null,
    status: "Nowy z metką",
    is_favourite: false,
    view_count: 0,
    performance: null,
    stats_visible: false,
    can_push_up: false,
    badge: null,
    size_guide_faq_entry_id: null,
    localization: "none",
    offline_verification: false,
    offline_verification_fee: null,
    icon_badges: []
};
